# Generated by Django 6.0

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0007_brand_wallet_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in brand\'s currency', max_digits=10)),
                ('currency', models.CharField(default='NGN', help_text='Currency code', max_length=3)),
                ('paystack_reference', models.CharField(help_text='Paystack transaction reference', max_length=100, unique=True)),
                ('paystack_authorization_code', models.CharField(blank=True, help_text='Paystack authorization code for future charges', max_length=100)),
                ('paystack_customer_code', models.CharField(blank=True, help_text='Paystack customer code', max_length=100)),
                ('payment_type', models.CharField(choices=[('wallet_topup', 'Wallet Top-up'), ('campaign_payment', 'Campaign Payment')], default='wallet_topup', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('description', models.TextField(blank=True, help_text='Payment description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['paystack_reference'], name='payments_pa_paystac_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_idx'),
        ),
    ]

