# Generated by Django 6.0 on 2025-12-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payments_pa_paystac_264859_idx',
            old_name='payments_pa_paystac_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payments_pa_status_c4e513_idx',
            old_name='payments_pa_status_idx',
        ),
    ]
