# Generated by Django 6.0 on 2025-12-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, help_text='Company description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='brand',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('request_info', 'Request Info')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
