# Generated by Django 6.0 on 2025-12-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_address_brand_contact_email_brand_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='phone_number',
            field=models.CharField(blank=True, help_text='International format: +1 (555) 123-4567', max_length=30),
        ),
    ]
