# Generated by Django 6.0 on 2025-12-21 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='pause_reason',
            field=models.TextField(blank=True, help_text='Reason for pausing the account'),
        ),
        migrations.AddField(
            model_name='brand',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='paused_by',
            field=models.ForeignKey(blank=True, help_text='Admin who paused this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paused_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('request_info', 'Request Info'), ('paused', 'Paused')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BrandVerificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(help_text='When to process this verification')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_queue', to='brands.brand')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
