# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


def migrate_industry_data(apps, schema_editor):
    """Migrate existing industry data to legacy field before changing the field type."""
    Brand = apps.get_model('brands', 'Brand')
    for brand in Brand.objects.all():
        if brand.industry:
            brand.industry_legacy = brand.industry
            brand.save(update_fields=['industry_legacy'])


def reverse_migrate_industry_data(apps, schema_editor):
    """Reverse migration - restore industry from legacy field."""
    Brand = apps.get_model('brands', 'Brand')
    for brand in Brand.objects.all():
        if brand.industry_legacy and not brand.industry:
            # This is a simplified reverse - we can't restore the ForeignKey easily
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_brand_pause_reason_brand_paused_at_brand_paused_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Industry name (e.g., Fashion, Technology, Food & Beverage)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this industry')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this industry is available for selection')),
                ('icon', models.CharField(blank=True, help_text="Icon name (e.g., 'lucide:shirt' for Fashion)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='industry_legacy',
            field=models.CharField(blank=True, help_text='Legacy industry field', max_length=100),
        ),
        migrations.RunPython(migrate_industry_data, reverse_migrate_industry_data),
        migrations.RemoveField(
            model_name='brand',
            name='industry',
        ),
        migrations.AddField(
            model_name='brand',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Primary industry/category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='brands.industry'),
        ),
    ]

