# Generated by Django 6.0 on 2025-12-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_populate_default_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Available balance for creating campaigns', max_digits=10),
        ),
    ]
