# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_brand_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., NGN, USD, EUR)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Currency name (e.g., Nigerian Naira, US Dollar)', max_length=50)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., ₦, $, €)', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default currency for new brands')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this currency is available for selection')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate to default currency (for conversion purposes)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency for wallet and payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='brands.currency'),
        ),
    ]

