# Generated by Django 6.0 on 2025-12-19 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('request_info', 'Request Info')], default='pending', max_length=20)),
                ('tier', models.CharField(blank=True, choices=[('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3')], max_length=20, null=True)),
                ('tiktok_handle', models.CharField(blank=True, max_length=100)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('youtube_handle', models.CharField(blank=True, max_length=100)),
                ('tiktok_followers', models.IntegerField(default=0)),
                ('instagram_followers', models.IntegerField(default=0)),
                ('youtube_subscribers', models.IntegerField(default=0)),
                ('sample_tiktok_link', models.URLField(blank=True, null=True)),
                ('sample_instagram_link', models.URLField(blank=True, null=True)),
                ('sample_youtube_link', models.URLField(blank=True, null=True)),
                ('niche', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
