# Generated by Django 6.0 on 2025-12-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Has completed initial onboarding'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Has completed profile setup'),
        ),
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('snapchat', 'Snapchat')], max_length=20)),
                ('handle', models.CharField(help_text='Platform handle (without @)', max_length=100)),
                ('followers_count', models.IntegerField(default=0, help_text='Number of followers/subscribers')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('failed', 'Verification Failed')], default='pending', max_length=20)),
                ('engagement_rate', models.FloatField(default=0.0, help_text='Engagement rate percentage')),
                ('avg_views', models.IntegerField(default=0, help_text='Average views per post')),
                ('sample_post_url', models.URLField(blank=True, help_text='Sample post for verification', null=True)),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token', null=True)),
                ('platform_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to='influencers.influencer')),
            ],
            options={
                'ordering': ['-followers_count'],
                'unique_together': {('influencer', 'platform')},
            },
        ),
    ]
