# Generated by Django 6.0 on 2025-12-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_influencer_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('snapchat', 'Snapchat')], help_text='Platform name', max_length=20, unique=True)),
                ('minimum_followers', models.IntegerField(default=5000, help_text='Minimum follower count required for this platform')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this platform is available for influencers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
                'ordering': ['platform'],
            },
        ),
        migrations.AddField(
            model_name='influencer',
            name='primary_platform',
            field=models.CharField(blank=True, choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('snapchat', 'Snapchat')], help_text='Primary platform the influencer wants to work on', max_length=20, null=True),
        ),
    ]
