# Generated by Django 6.0 on 2025-12-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_populate_platform_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconnection',
            name='verification_confidence',
            field=models.FloatField(default=0.0, help_text='Confidence score from automated verification (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='verification_flags',
            field=models.JSONField(blank=True, default=list, help_text='List of flags/warnings from automated verification'),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='verification_method',
            field=models.CharField(choices=[('auto', 'Automated'), ('manual', 'Manual Review'), ('api', 'Platform API')], default='auto', help_text='Method used for verification', max_length=20),
        ),
    ]
