# Generated by Django 6.0 on 2025-12-19 17:45

import django.db.models.deletion
from django.db import migrations, models


def migrate_niche_data(apps, schema_editor):
    """Migrate existing niche data to legacy field before changing the field type."""
    Influencer = apps.get_model('influencers', 'Influencer')
    for influencer in Influencer.objects.all():
        if influencer.niche:
            influencer.niche_legacy = influencer.niche
            influencer.save(update_fields=['niche_legacy'])


def reverse_migrate_niche_data(apps, schema_editor):
    """Reverse migration - restore niche from legacy field."""
    Influencer = apps.get_model('influencers', 'Influencer')
    for influencer in Influencer.objects.all():
        if influencer.niche_legacy and not influencer.niche:
            # This is a simplified reverse - we can't restore the ForeignKey easily
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0005_platformconnection_verification_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Niche name (e.g., Fashion, Fitness, Tech)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this niche')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this niche is available for selection')),
                ('icon', models.CharField(blank=True, help_text="Icon name (e.g., 'lucide:shirt' for Fashion)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Niche',
                'verbose_name_plural': 'Niches',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='influencer',
            name='niche_legacy',
            field=models.CharField(blank=True, help_text='Legacy niche field', max_length=100),
        ),
        migrations.RunPython(migrate_niche_data, reverse_migrate_niche_data),
        migrations.RemoveField(
            model_name='influencer',
            name='niche',
        ),
        migrations.AddField(
            model_name='influencer',
            name='niche',
            field=models.ForeignKey(blank=True, help_text='Primary niche/category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencers', to='influencers.niche'),
        ),
    ]
