# Generated by Django 6.0 on 2025-12-21 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_populate_default_niches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='pause_reason',
            field=models.TextField(blank=True, help_text='Reason for pausing the account'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='paused_by',
            field=models.ForeignKey(blank=True, help_text='Admin who paused this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paused_influencers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('request_info', 'Request Info'), ('paused', 'Paused')], default='pending', max_length=20),
        ),
    ]
