# Generated by Django 6.0 on 2025-12-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0007_influencer_pause_reason_influencer_paused_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerVerificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(help_text='When to process this verification')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_queue', to='influencers.influencer')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
