# Generated by Django 6.0 on 2025-12-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0008_influencerverificationqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconnection',
            name='follower_verification_date',
            field=models.DateTimeField(blank=True, help_text='When follower count was last verified from API', null=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='verified_followers_count',
            field=models.IntegerField(blank=True, help_text='Actual follower count verified from platform API', null=True),
        ),
        migrations.AlterField(
            model_name='platformconnection',
            name='followers_count',
            field=models.IntegerField(default=0, help_text='Number of followers/subscribers (user-provided)'),
        ),
    ]
