# Generated by Django 6.0 on 2025-12-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0009_platformconnection_follower_verification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconnection',
            name='facebook_page_id',
            field=models.CharField(blank=True, help_text='Facebook Page ID (for Facebook/Instagram OAuth)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='instagram_business_account_id',
            field=models.CharField(blank=True, help_text='Instagram Business Account ID (from OAuth)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='oauth_connected_at',
            field=models.DateTimeField(blank=True, help_text='When OAuth connection was established', null=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the OAuth token expires', null=True),
        ),
        migrations.AlterField(
            model_name='platformconnection',
            name='platform_user_id',
            field=models.CharField(blank=True, help_text='Platform user/account ID', max_length=100, null=True),
        ),
    ]
