# Generated by Django 6.0 on 2025-12-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0010_add_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconnection',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='OAuth refresh token (for token renewal)', null=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='tiktok_open_id',
            field=models.CharField(blank=True, help_text='TikTok Open ID (from OAuth)', max_length=100, null=True),
        ),
    ]
