# Generated by Django 6.0 on 2025-12-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0011_add_tiktok_oauth_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='primary_platform',
            field=models.CharField(blank=True, choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('snapchat', 'Snapchat'), ('facebook', 'Facebook')], help_text='Primary platform the influencer wants to work on', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='platformconnection',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('snapchat', 'Snapchat'), ('facebook', 'Facebook')], max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('snapchat', 'Snapchat'), ('facebook', 'Facebook')], help_text='Platform name', max_length=20, unique=True),
        ),
    ]
