# Generated by Django 6.0 on 2025-12-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0013_update_minimum_followers_to_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='bio',
            field=models.TextField(blank=True, help_text='Bio/About me description'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (recommended size: 400x400px)', null=True, upload_to='influencers/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='minimum_followers',
            field=models.IntegerField(default=1000, help_text='Minimum follower count required for this platform'),
        ),
    ]
