# Generated by Django 6.0 on 2025-12-29 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0011_brand_logo'),
        ('influencers', '0014_influencer_bio_influencer_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency for wallet and payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencers', to='brands.currency'),
        ),
    ]
