# Generated by Django 6.0 on 2025-12-31 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0016_set_default_currency_for_influencers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('bank', 'Bank Transfer'), ('momo', 'Mobile Money')], help_text='Type of payment method', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default payment method for withdrawals')),
                ('bank_name', models.CharField(blank=True, help_text='Bank name (for bank transfer)', max_length=200)),
                ('account_number', models.CharField(blank=True, help_text='Account number (for bank transfer)', max_length=50)),
                ('account_name', models.CharField(blank=True, help_text='Account holder name (for bank transfer)', max_length=200)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code (optional, for international transfers)', max_length=20)),
                ('bank_country', models.CharField(blank=True, default='Ghana', help_text='Country where bank is located', max_length=100)),
                ('mobile_money_network', models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('vodafone', 'Vodafone Cash'), ('airteltigo', 'AirtelTigo Money'), ('other', 'Other')], help_text='Mobile Money network (for Ghana)', max_length=20)),
                ('mobile_money_number', models.CharField(blank=True, help_text='Mobile Money phone number (e.g., 0244123456)', max_length=20)),
                ('mobile_money_name', models.CharField(blank=True, help_text='Name registered with Mobile Money account', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(help_text='Influencer who owns this payment method', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='influencers.influencer')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
