# Generated by Django 6.0 on 2025-12-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_duplicate_emails'),  # Run duplicate cleanup first
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address (must be unique across all accounts).', max_length=254, unique=True),
        ),
    ]
